services:
  joomla:
    image: joomla:5.2
    container_name: joomla_app
    ports:
      - "8080:80"
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: joomla_user
      JOOMLA_DB_PASSWORD: joomla_password
      JOOMLA_DB_NAME: joomla_db
    volumes:
      - ./joomla:/var/www/html
      - ../com_jsonapiclient/site:/var/www/html/components/com_jsonapiclient
      - ../com_jsonapiclient/administrator:/var/www/html/administrator/components/com_jsonapiclient
      - ../com_jsonapiclient/compose.yml:/var/www/html/administrator/components/com_jsonapiclient/compose.yml
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:11.0
    container_name: joomla_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: joomla_db
      MYSQL_USER: joomla_user
      MYSQL_PASSWORD: joomla_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: