<?php

namespace Joomla\Component\JsonApiClient\Site\Controller;

use Joomla\CMS\MVC\Controller\BaseController;

/**
 * @package     ${NAMESPACE}
 * @subpackage
 *
 * @copyright   A copyright
 * @license     A "Slug" license name e.g. GPL2
 */
class DisplayController extends BaseController
{
	protected $default_view = 'welcome';

	public function display($cachable = false, $urlparams = [])
	{
		return parent::display($cachable, $urlparams); // TODO: Change the autogenerated stub
	}


}